env: nav_2d         # continuous navigation 2d 
vw:
  - x: 0.5
    thickness: 0.02
    holes:
      - center: 0.3
        height: 0.1
      - center: 0.7
        height: 0.2

hw:
  - y: 0.5
    thickness: 0.02
    holes:
      - center: 0.3
        width: 0.1
      - center: 0.7
        width: 0.2


alg: sac_sf            # type algo : ppo, dqn, sacd or lsfm
lr: 1.0e-3          # learning rate
it: !!float 15000   # number of interations
bs: 300             # batch_size if off policy
lf: 1.              # exploration policy + SFcritic learning only 

# ec: 1.              # no entropy calculation