env: nav_2d # continuous navigation 2d 
nenv: 1
vw:
  - x: 0.5
    thickness: 0.02
    holes:
      - center: 0.3
        height: 0.1
      - center: 0.7
        height: 0.2

hw:
  - y: 0.5
    thickness: 0.02
    holes:
      - center: 0.3
        width: 0.1
      - center: 0.7
        width: 0.2

alg: dreamerv3            # type algo : ppo, dqn, sacd or lsfm
lr: 1.0e-3          # learning rate
it: !!float 50000   # number of interations
bs: 300             # batch_size if off policy
learning_starts: 3000
policy: MlpPolicy
features_extractor_kwargs: 
  features_dim: 32
  net_arch: 
  - 4
  - 8
  - 16
  - 32
  - 64

actor:
  random: false # RANDOM ACTION !!!
  # net_arch: [400, 400]
  net_arch: 
  - 64
  - 64

critic:
  # net_arch: [400, 400, 400]
  net_arch: 
    - 64
    - 64

latent_classes: 16
latent_length:  16
# recurrent_size:  512
recurrent_size:  32

recurrent_model:
  # hidden_size: 200
  hidden_size: 64

prior_net:
  # net_arch: [200]
  net_arch: 
  - 64
  uniform_mix: 0.01

posterior_net:
  # net_arch: [200]
  net_arch: 
  - 64
  uniform_mix: 0.01

reward_net:
  # net_arch: [400, 400]
  net_arch: 
  - 64
  - 64

continue_net:
  # net_arch: [400, 400, 400]
  net_arch: 
    - 64
    - 64
