env: nav_2d         # continuous navigation 2d 
vw:
  - x: 0.5
    holes:
      - center: 0.5
        height: 0.7
      # - center: 0.7
      #   height: 0.2

hw:
  - y: 0.5
    holes:      
      - center: 0.5
        width: 0.7
      # - center: 0.3
      #   width: 0.1
      # - center: 0.7
      #   width: 0.2
bl: 0.
bh: 1.
gp: "[0.1,0.1]"

sl: True

alg: ppo_sf            # type algo : ppo, dqn, sacd or lsfm
lr: 3.0e-4          # learning rate
it: !!float 50000   # number of interations
bs: 300             # batch_size if off policy
sfe: True           # share_features_extractor
na: "[64,64]"
ec: 0.